### ISSUE TITLE
起動時例外 blender 2.83

### ISSUE THREAD

**Issue by listelin** [trzr/Blender-CM3D2-Converter#2]
早速の対応ありがとうございます。
が、typoがあるようです

  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\CM3D2 Converter\__init__.py", line 4
    "version": (2020, 6, 8, 0, 3, 16),54),
SyntaxError: invalid syntax

**Comment by trzr** [comment]
申し訳ないです。
簡単な確認の後、スクリプトで日付挿入していた部分でおかしくなっていたようです。
修正しました。

もし、問題がなかったらIssueをクローズしてください。

**Comment by listelin** [comment]
ありがとうございました！
